name: Build
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'adopt'
          java-version: '11'

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
#      - uses: ./.github/actions/inflate-secrets
#        name: Inflate Secrets
#        with:
#          keystore: ${{ secrets.ORIGINAL_KEYSTORE_FILE }}
#          google-services: ${{ secrets.GOOGLESERVICES }}
#          firebase-creds: ${{ secrets.FIREBASECREDS }}
#          playstore-creds: ${{ secrets.PLAYSTORECREDS }}

      - name: set env
        run: echo “NOW=$(date +'%Y%m%d.%H%M%S')” >> $GITHUB_ENV
       
      - name: Build Release
#        env:
#          KEYSTORE_PASSWORD: ${{ secrets.ORIGINAL_KEYSTORE_FILE_PASSWORD }}
#          KEYSTORE_ALIAS: ${{ secrets.ORIGINAL_KEYSTORE_ALIAS }}
#          KEYSTORE_ALIAS_PASSWORD: ${{ secrets.ORIGINAL_KEYSTORE_ALIAS_PASSWORD }}
#          VERSION: ${{ steps.rel_number.outputs.version }}
#          VERSION_CODE: ${{ steps.rel_number.outputs.version-code }}
        run: ./gradlew assembleRelease
            
      - name: Create Github Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: tag6
          release_name: name6
          draft: false
          prerelease: false

      - name: Upload1
        uses: actions/upload-artifact@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Build Artifacts
          path: ./base/build/outputs/apk/release/base-release.apk  
          
      - name: Upload2
        uses: actions/upload-artifact@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Build Artifacts
          path: ./base/build/outputs/apk/release/base.apk
  
      - name: Upload Base APK
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./base/build/outputs/apk/release/base-release.apk
          asset_name: complications-base-5.apk
          asset_content_type: application/zip
          
      - name: Upload Full APK
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./base/build/outputs/apk/release/base-release.apk
          asset_name: complications-full-5.apk
          asset_content_type: application/zip
