name: Delete Tag

on: workflow_dispatch

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: false
          tag_name: test6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: false
          tag_name: test7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: false
          tag_name: test8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: false
          tag_name: tag6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
