name: Delete Tag

on: workflow_dispatch

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: false
          tag_name: test2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: false
          tag_name: test3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: false
          tag_name: test4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: false
          tag_name: test5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
