name: Echo Time

on: workflow_dispatch

jobs:
  display:
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as env variable
        run: echo "OUTPUT=output-$(date "+%Y.%m.%d-%H.%M.%S")" >> $GITHUB_ENV
      - name: Echo current date
        run: echo ${{ env.OUTPUT }}
